version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.cloud:google-cloud-bom
    versions:
    - 0.147.0
    - 0.148.0
    - 0.149.0
    - 0.150.0
    - 0.151.0
    - 0.152.0
  - dependency-name: com.diffplug.spotless:spotless-maven-plugin
    versions:
    - 2.10.0
    - 2.10.1
    - 2.7.0
  - dependency-name: com.google.api-client:google-api-client
    versions:
    - 1.31.2
    - 1.31.3
  - dependency-name: org.typelevel:cats-kernel_2.12
    versions:
    - 2.3.1
    - 2.4.0
    - 2.4.1
    - 2.5.0
  - dependency-name: com.google.auto.value:auto-value-annotations
    versions:
    - 1.7.4
    - 1.7.5
  - dependency-name: io.grpc:grpc-protobuf
    versions:
    - 1.36.1
  - dependency-name: io.grpc:grpc-netty
    versions:
    - 1.36.1
  - dependency-name: io.grpc:grpc-stub
    versions:
    - 1.36.1
  - dependency-name: io.grpc:grpc-auth
    versions:
    - 1.36.1
  - dependency-name: io.grpc:grpc-core
    versions:
    - 1.36.1
  - dependency-name: io.grpc:grpc-context
    versions:
    - 1.36.1
  - dependency-name: io.grpc:grpc-all
    versions:
    - 1.36.1
  - dependency-name: org.tensorflow:tensorflow-core-platform
    versions:
    - 0.3.0
  - dependency-name: com.spotify:featran-tensorflow_2.12
    versions:
    - 0.8.0-RC2
  - dependency-name: com.spotify:featran-java_2.12
    versions:
    - 0.8.0-RC2
  - dependency-name: com.spotify:featran-core_2.12
    versions:
    - 0.8.0-RC2
  - dependency-name: com.google.auth:google-auth-library-oauth2-http
    versions:
    - 0.24.0
    - 0.25.0
  - dependency-name: com.google.auth:google-auth-library-credentials
    versions:
    - 0.24.0
    - 0.25.0
  - dependency-name: com.google.http-client:google-http-client
    versions:
    - 1.39.1
  - dependency-name: com.google.http-client:google-http-client-jackson2
    versions:
    - 1.39.1
  - dependency-name: com.google.protobuf:protobuf-java-util
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
  - dependency-name: com.google.apis:google-api-services-ml
    versions:
    - v1-rev20210206-1.31.0
  - dependency-name: org.scala-lang:scala-reflect
    versions:
    - 2.13.4
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.4
  - dependency-name: com.spotify.metrics:semantic-metrics-core
    versions:
    - 1.1.6
  - dependency-name: net.alchim31.maven:scala-maven-plugin
    versions:
    - 4.4.0
  - dependency-name: org.codehaus.gmaven:groovy-maven-plugin
    versions:
    - 2.1.1
